function data = import_NSWCCD(filename, dataLines)
%import_NSWCCD Import data from a text file
%  data = import_NSWCCD(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  data = import_NSWCCD(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  data = import_NSWCCD("/Users/rcoe/Downloads/awdc-t05-s00076.csv", [21, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Nov-2023 14:53:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [21, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 26);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "UTCTime", "TAITime", "ElapsedTime", "BRIDGEPROBE01", "BRIDGEPROBE03", "BRIDGEPROBE04", "BRIDGEPROBE05", "BRIDGEPROBE06", "BRIDGEPROBE08", "DIRECTIONALARRAY01", "DIRECTIONALARRAY02", "DIRECTIONALARRAY03", "DIRECTIONALARRAY04", "DIRECTIONALARRAY05", "DIRECTIONALARRAY06", "DIRECTIONALARRAY07", "DIRECTIONALARRAY08", "DIRECTIONALARRAY09", "DIRECTIONALARRAY10", "DIRECTIONALARRAY11", "DIRECTIONALARRAY12", "WAVEMAKERPULSE", "SINESIGNAL", "TTLTrigger", "VarName26"];
opts.SelectedVariableNames = ["UTCTime", "TAITime", "ElapsedTime", "BRIDGEPROBE01", "BRIDGEPROBE03", "BRIDGEPROBE04", "BRIDGEPROBE05", "BRIDGEPROBE06", "BRIDGEPROBE08", "DIRECTIONALARRAY01", "DIRECTIONALARRAY02", "DIRECTIONALARRAY03", "DIRECTIONALARRAY04", "DIRECTIONALARRAY05", "DIRECTIONALARRAY06", "DIRECTIONALARRAY07", "DIRECTIONALARRAY08", "DIRECTIONALARRAY09", "DIRECTIONALARRAY10", "DIRECTIONALARRAY11", "DIRECTIONALARRAY12", "WAVEMAKERPULSE", "SINESIGNAL", "TTLTrigger"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

% Format time columns
fileID = fopen(filename,'r');
frewind(fileID)
D = textscan(fileID,'%s\t%f',1,'headerlines',1);
dd = D{2};
T = textscan(fileID,'%s\t%s',1,'headerlines',1);
tt = T{2}{1};
stime = datetime([num2str(dd),'-',tt],'InputFormat','yyyyMMdd-HH:mm:ss');
data.UTCTime = datetime(string(stime,'yyyy-MM-dd-') ...
    + num2str(data.UTCTime),'InputFormat','yyyy-MM-dd-HHmmss.SSSSSS');
data.TAITime = datetime(data.TAITime/1e9,'convertfrom','posix');

end